version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: chronos-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chronos
    ports:
      - "5432:5432"
    volumes:
      - chronos_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: chronos-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dinu2001maharana@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: chronos-keycloak
    restart: always
    environment:
      KC_DB: h2
      KC_HTTP_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  chronos_pgdata:
  pgadmin_data:
